version: "3"

services:
  loki:
    image: grafana/loki:1.4.0
    restart: on-failure
    ports:
      - "3100:3100"

  promtail:
    build:
      context: .
      dockerfile: promtail-test.Dockerfile
    env_file:
      - docker-compose.integration-test.env
    command: ["--tags", "external", "./..."]
    depends_on:
      - loki
