name: Continious Integration
on:
  push:
    branches:
      - master
      - development
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Lint the code
        run: |
          make install-linter
          make run-linter
